use crate::types::*;

/// This object contains full information about a chat.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct ChatFullInfo {
    pub id: Integer,
    #[serde(rename = "type")]
    pub type_: String,
    pub title: Option<String>,
    pub username: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub is_forum: Option<bool>,
    pub accent_color_id: Option<Integer>,
    pub max_reaction_count: Option<Integer>,
    pub photo: Option<super::chat_photo::ChatPhoto>,
    pub active_usernames: Option<Vec<String>>,
    pub birthdate: Option<super::birthdate::Birthdate>,
    pub business_intro: Option<super::business::BusinessIntro>,
    pub business_location: Option<super::business::BusinessLocation>,
    pub business_opening_hours: Option<super::business::BusinessOpeningHours>,
    pub personal_chat: Option<Chat>,
    pub available_reactions: Option<Vec<super::reaction_type::ReactionType>>,
    pub background_custom_emoji_id: Option<String>,
    pub profile_accent_color_id: Option<Integer>,
    pub profile_background_custom_emoji_id: Option<String>,
    pub emoji_status_custom_emoji_id: Option<String>,
    pub emoji_status_expiration_date: Option<Integer>,
    pub bio: Option<String>,
    pub has_private_forwards: Option<bool>,
    pub has_restricted_voice_and_video_messages: Option<bool>,
    pub join_to_send_messages: Option<bool>,
    pub join_by_request: Option<bool>,
    pub description: Option<String>,
    pub invite_link: Option<String>,
    pub pinned_message: Option<Box<MessageOrChannelPost>>,
    pub permissions: Option<super::chat_permissions::ChatPermissions>,
    pub can_send_paid_media: Option<bool>,
    pub slow_mode_delay: Option<Integer>,
    pub unrestrict_boost_count: Option<Integer>,
    pub message_auto_delete_time: Option<Integer>,
    pub has_aggressive_anti_spam_enabled: Option<bool>,
    pub has_hidden_members: Option<bool>,
    pub has_protected_content: Option<bool>,
    pub has_visible_history: Option<bool>,
    pub sticker_set_name: Option<String>,
    pub can_set_sticker_set: Option<bool>,
    pub custom_emoji_sticker_set_name: Option<String>,
    pub linked_chat_id: Option<Integer>,
    pub location: Option<super::chat_location::ChatLocation>,
    pub is_direct_messages: Option<bool>,
    pub parent_chat: Option<Chat>,
    pub accepted_gift_types: Option<super::unique_gift::AcceptedGiftTypes>,
    pub paid_message_star_count: Option<Integer>,
}
